version: "3.8"

services:
  nextjs:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - proxy
    ports:
      - 3000:3000
    networks:
      - stwrkng
  proxy:
    image: staticfloat/nginx-certbot
    restart: always
    environment:
      CERTBOT_EMAIL: "aprosvirov093@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - stwrkng
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./certbot_extra_domains:/etc/nginx/certbot/extra_domains:ro

networks:
  stwrkng:
    driver: bridge
